select * from customer 

-- Q1. What is the total revenue generated by female vs male customers?
select gender, SUM(purchase_amount) as revenue
from customer 
group by gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select TOP 5 item_purchased, 
ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer 
group by item_purchased 
order by avg(review_rating) desc

 -- products with consistent higher ratings can be hihglited in marketing campaigns and also sold at premium price

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type


-- Q5. Do subscribed customers spend more? Compare average spend and total 
-- revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- the average spend of subscribers and non-subscribers is similar, but the total revenue of the 
-- non-subscribers is much higher

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied? 
-- i.e. which products rely heavily on discount to sell
select TOP 5 item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) AS discount_rate
from customer 
group by item_purchased
order by discount_rate desc

-- if hats were sold, 50% of the time a discount was used


-- Q7. Segment customers into New, Returning, and Loyal based on their total amount of previous purchases.
with customer_type as(
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3
order by category, item_rank;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


-- Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

-- young adults drive the most revenue followed by middle-aged customers.